<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_JMeter Beginner Tutorial 1 - How to _cb7171</name>
   <tag></tag>
   <elementGuidId>0d003b6f-caed-4f06-b0e2-de2a16677814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yotu-player-6519c0cb88557</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='yotu-player-6519c0cb88557']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>98355a98-4c6a-4895-a91d-ee71faba6a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yotu-video-placeholder</value>
      <webElementGuid>bb53f302-402a-4f68-9c44-097bc361ce4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yotu-player-6519c0cb88557</value>
      <webElementGuid>4f21f46b-f290-422a-8f17-7014f1480b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>841311eb-65e5-4a22-aab2-410cf7a478e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>13f21a12-1f0c-4033-a23c-8257d4b52644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share</value>
      <webElementGuid>2c2e8dcb-88a1-4d63-a5d3-7316e2e8b230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>JMeter Beginner Tutorial 1 - How to install Jmeter</value>
      <webElementGuid>564d80d4-9131-4de2-90f0-7eca85e3c01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>c589ad00-9739-4d9b-a0ae-597abcc1c200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>29b36401-00fb-4676-b976-2b5c32073caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/M-iAXz8vs48?controls=1&amp;modestbranding=0&amp;loop=0&amp;autonext=0&amp;showinfo=1&amp;rel=1&amp;thumbnails=1&amp;cc_load_policy=1&amp;cc_lang_pref=1&amp;hl&amp;iv_load_policy=1&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fautomationstepbystep.com&amp;widgetid=1</value>
      <webElementGuid>ce5f97d0-184e-4de0-bfd8-25ad39b1b729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yotu-player-6519c0cb88557&quot;)</value>
      <webElementGuid>980440e8-cde6-4db6-ac9e-eb0e57e5dbf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='yotu-player-6519c0cb88557']</value>
      <webElementGuid>14e6a046-bd42-40e0-9f17-b2cbf1d06cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yotuwp-6519c0cb221d6']/div/div/div[2]/iframe</value>
      <webElementGuid>567b4eaf-a78a-48ef-bdbe-9c4967f15044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>93df0039-c739-4501-85db-e536c7bf0924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'yotu-player-6519c0cb88557' and @title = 'JMeter Beginner Tutorial 1 - How to install Jmeter' and @src = 'https://www.youtube.com/embed/M-iAXz8vs48?controls=1&amp;modestbranding=0&amp;loop=0&amp;autonext=0&amp;showinfo=1&amp;rel=1&amp;thumbnails=1&amp;cc_load_policy=1&amp;cc_lang_pref=1&amp;hl&amp;iv_load_policy=1&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fautomationstepbystep.com&amp;widgetid=1']</value>
      <webElementGuid>220ba269-8e1a-4ac6-a2e8-775ffc0dd215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
