<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Unassigned_DDVe7KpC</name>
   <tag></tag>
   <elementGuidId>6dde4b9f-a959-4fd2-a354-a3753b1d6443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DDVe7KpC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='DDVe7KpC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>9773fabf-b653-43e1-99b7-1d9809f50caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DDVe7KpC</value>
      <webElementGuid>5aede7f5-a71a-4a48-9358-2ff722277a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>407</value>
      <webElementGuid>c48c42b2-26d5-44f8-a755-f3882355fd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>331</value>
      <webElementGuid>e5a557d1-ae6d-4187-8906-ce45e3326a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DDVe7KpC&quot;)</value>
      <webElementGuid>a902756b-a8a8-4159-b9d3-694cdad21ee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='DDVe7KpC']</value>
      <webElementGuid>4be1b7e1-d48e-427c-a2bc-84e509be1e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[7]/div/div[2]/div/div/canvas</value>
      <webElementGuid>42510b04-0ff5-4a6d-abdb-4608d5784105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/canvas</value>
      <webElementGuid>34fc72c9-6d2f-488b-876e-d728b9574f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'DDVe7KpC']</value>
      <webElementGuid>a9ea5fd1-5aec-4eed-ac08-9458364995b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
